# Comedi "helper" modules
obj-m		+= comedi_8254.o

# Comedi misc drivers
obj-m		+= comedi_bond.o
obj-m		+= comedi_test.o
obj-m		+= comedi_parport.o

# Comedi USB drivers
obj-m		+= dt9812.o
obj-m		+= ni_usb6501.o
obj-m		+= usbdux.o
obj-m		+= usbduxfast.o
obj-m	+= usbduxsigma.o
obj-m		+= vmk80xx.o
